# This is a basic workflow to help you get started with the Run Jtest action.
name: Jtest with Gradle

on:
  # Trigger the workflow on push or pull request events but only for the main branch.
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel.
jobs:
  build:
    name: Analyze project with Jtest
    
    permissions:
      # required for all workflows
      security-events: write
      
    # Specifies the type of runner that the job will run on.
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job.
    steps:
    
    # Checks out your repository under $GITHUB_WORKSPACE, so that your job can access it.
    - name: Checkout repository
      uses: actions/checkout@v4
      #uses: actions/checkout@v5
      # === IMPORTANT ===
      # below actions/checkout@v6 has option ref which refing to direcotory/workspace of the runner or can refer to main brach like below
      # it means that ref:main refers to the original repository, 
      # where non ref or ref:${{ github.workspace }} refers to workspase of the runner where timestamp of files are modify
      # and Test Configuration of Parasoft tool may have conflict using date filter
      # =====
      #uses: actions/checkout@v6
      with:
    # Repository name with owner. For example, actions/checkout
       #Default: ${{ github.repository }}
       #path: d:\workspace\github\demo
       #path: d:/workspace/github/demo
       path: .
       ref: ${{ github.workspace }}
       #ref: "d:/workspace/github/demo"
       #ref: ${{ github.repository }}
       #ref: main
       #workspace: "d:/workspace/github/demo"
       #set-safe-directory: 'd:/workspace/github/demo2'
       set-safe-directory: 'C:/actions-runner2331_jtest2025.2.2/_work/jtest_demo/jtest_demo'
       repository: stingerBoo/jtest_demo
       #token: ${{ secrets.GIT_TECHDEPLOY_TOKEN }}
       #path: infrastructure-helm
       fetch-depth: 0
      
    # Checks out github.workspace  
    - name: Check github.workspace
      id: full-workspace
      shell: bash
      run: |
        PATH="${{ github.workspace }}"
        echo "path=$PATH" >> $GITHUB_OUTPUT
        echo "Full workspace path: $PATH"  
    - name: Modified files Simple.java
      run: |
          git blame src/main/java/examples/eval/Simple.java
    # Generates the jtest.data.json input file.
    - name: Create input for Jtest      
      shell: cmd      
      #working-directory: d:\workspace\github\demo
      #working-directory: d:/workspace/github/demo
      #run: .\gradlew clean build jtest -I c:/Parasoft/jtest/2025.1.1/integration/gradle/init.gradle "-Djtest.config=user://RR_modify1"
      #run: .\gradlew clean build jtest -I c:/Parasoft/jtest/2025.2.2/integration/gradle/init.gradle "-Djtest.config=builtin://Recommended Rules"
      #run: .\gradlew clean build jtest -I c:/Parasoft/jtest/2025.2.2/integration/gradle/init.gradle "-Djtest.config=user://Test_13"
      run: .\gradlew clean build jtest -I c:/Parasoft/jtest/2025.2.2/integration/gradle/init.gradle "-Djtest.config=user://2026-02-11_testModify"
      #run: .\gradlew clean build jtest -I c:/Parasoft/jtest/2025.1.1/integration/gradle/init.gradle "-Djtest.config=user://RR_modify1"
      #working-directory: d:/workspace/github/demo
      #working-directory: C:/actions-runner2331_jtest2025.2.2/_work/jtest_demo/jtest_demo

    # Runs code analysis with Jtest.
    #- name: Run Jtest
    #  id: jtest
    #  uses: parasoft/run-jtest-action@2.0.2
    #  with:
    #    #Uses the jtest.data.json generated with the Gradle command in the previous step
    #    input: build/jtest/jtest.data.json
